# Generated by Django 3.1.6 on 2021-02-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('methods', models.TextField()),
            ],
            options={
                'verbose_name': 'Психотерапевта',
                'verbose_name_plural': 'Психотерапевты',
            },
        ),
    ]
